"""add slurm_group_id to workflow

Revision ID: 299f48f5a6e5
Revises: addc0edea736
Create Date: 2026-05-13 12:48:05.023378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299f48f5a6e5'
down_revision: Union[str, None] = 'addc0edea736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('slurm_group_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'slurm_group_id')
    # ### end Alembic commands ###
