"""rename slurm_group_id to cluster_group_id

Revision ID: 642dd4604a7b
Revises: 299f48f5a6e5
Create Date: 2026-05-13 14:54:25.749958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642dd4604a7b'
down_revision: Union[str, None] = '299f48f5a6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('cluster_group_id', sa.String(), nullable=True))
    op.drop_column('workflows', 'slurm_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('slurm_group_id', sa.VARCHAR(), nullable=True))
    op.drop_column('workflows', 'cluster_group_id')
    # ### end Alembic commands ###
