"""add cluster_group_id to workflow

Revision ID: 831ac8f8481d
Revises: addc0edea736
Create Date: 2026-05-13 15:29:22.530583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831ac8f8481d'
down_revision: Union[str, None] = 'addc0edea736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('cluster_group_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'cluster_group_id')
    # ### end Alembic commands ###
